package com.bolen.seckill.dao.mapper;

import java.util.List;

import com.bolen.seckill.dao.model.SeckillProduct;

public interface SeckillProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_product
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_product
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	int insert(SeckillProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_product
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	int insertSelective(SeckillProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_product
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	SeckillProduct selectByPrimaryKey(Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_product
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	int updateByPrimaryKeySelective(SeckillProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_product
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	int updateByPrimaryKey(SeckillProduct record);

	List<SeckillProduct> findByNo(String promotionNO);
}