package com.bolen.seckill.dao.mapper;

import java.util.Map;

import com.bolen.seckill.dao.model.SeckillOrder;

public interface SeckillOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_order
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	int deleteByPrimaryKey(Integer oid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_order
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	int insert(SeckillOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_order
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	int insertSelective(SeckillOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_order
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	SeckillOrder selectByPrimaryKey(Integer oid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_order
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	int updateByPrimaryKeySelective(SeckillOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill_order
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	int updateByPrimaryKey(SeckillOrder record);
	
	
	int updateUnPayed(Map map);
}