package com.bolen.seckill.dao.model;

import java.util.Date;

public class SeckillProduct {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_product.pid
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_product.amount
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	private Integer amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_product.start_time
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_product.special_price
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	private Double specialPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_product.promotion_no
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	private String promotionNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_product.pid
	 * @return  the value of seckill_product.pid
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_product.pid
	 * @param pid  the value for seckill_product.pid
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_product.amount
	 * @return  the value of seckill_product.amount
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_product.amount
	 * @param amount  the value for seckill_product.amount
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_product.start_time
	 * @return  the value of seckill_product.start_time
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_product.start_time
	 * @param startTime  the value for seckill_product.start_time
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_product.special_price
	 * @return  the value of seckill_product.special_price
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public Double getSpecialPrice() {
		return specialPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_product.special_price
	 * @param specialPrice  the value for seckill_product.special_price
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public void setSpecialPrice(Double specialPrice) {
		this.specialPrice = specialPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_product.promotion_no
	 * @return  the value of seckill_product.promotion_no
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public String getPromotionNo() {
		return promotionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_product.promotion_no
	 * @param promotionNo  the value for seckill_product.promotion_no
	 * @mbggenerated  Mon Apr 02 17:36:52 CST 2018
	 */
	public void setPromotionNo(String promotionNo) {
		this.promotionNo = promotionNo;
	}
}