package com.bolen.seckill.dao.model;

import java.util.Date;

public class SeckillOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_order.oid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	private Integer oid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_order.pid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_order.uid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_order.status
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_order.create_time
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seckill_order.price
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	private Double price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_order.oid
	 * @return  the value of seckill_order.oid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public Integer getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_order.oid
	 * @param oid  the value for seckill_order.oid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public void setOid(Integer oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_order.pid
	 * @return  the value of seckill_order.pid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_order.pid
	 * @param pid  the value for seckill_order.pid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_order.uid
	 * @return  the value of seckill_order.uid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_order.uid
	 * @param uid  the value for seckill_order.uid
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_order.status
	 * @return  the value of seckill_order.status
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_order.status
	 * @param status  the value for seckill_order.status
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_order.create_time
	 * @return  the value of seckill_order.create_time
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_order.create_time
	 * @param createTime  the value for seckill_order.create_time
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill_order.price
	 * @return  the value of seckill_order.price
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill_order.price
	 * @param price  the value for seckill_order.price
	 * @mbggenerated  Thu Apr 05 16:25:28 CST 2018
	 */
	public void setPrice(Double price) {
		this.price = price;
	}
}